const express = require('express');
const PDFDocument = require('pdfkit');
const router = express.Router();

router.get('/statement', async (req, res) => {
  const doc = new PDFDocument({ margin: 50 });

  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', 'inline; filename=bank-statement.pdf');

  doc.pipe(res);

  doc
    .fontSize(20)
    .text('Corporate Banking Statement', { align: 'center' });

  doc.moveDown();
  doc.fontSize(12).text('Account Holder: Raja Zahid Hussain');
  doc.text('Login ID: MFCB0329');
  doc.text('Statement Date: ' + new Date().toLocaleDateString());

  doc.moveDown();
  doc.fontSize(14).text('Account Summary', { underline: true });
  doc.moveDown(0.5);
  doc.fontSize(12).text('Total Balance: 826,500');
  doc.text('Currency: Mixed');

  doc.moveDown();
  doc.fontSize(14).text('Recent Transactions', { underline: true });
  doc.moveDown(0.5);

  doc.fontSize(11);
  doc.text('Date', 50, doc.y, { continued: true });
  doc.text('Description', 150, doc.y, { continued: true });
  doc.text('Amount', 400, doc.y, { continued: true });
  doc.text('Currency', 480, doc.y);

  doc.moveDown(0.5);
  doc.text('2026-03-30', 50, doc.y, { continued: true });
  doc.text('Opening Balance', 150, doc.y, { continued: true });
  doc.text('800000', 400, doc.y, { continued: true });
  doc.text('PKR', 480, doc.y);

  doc.text('2026-03-30', 50, doc.y, { continued: true });
  doc.text('Cash Wallet', 150, doc.y, { continued: true });
  doc.text('1500', 400, doc.y, { continued: true });
  doc.text('GBP', 480, doc.y);

  doc.moveDown();
  doc.text('Generated by Corporate Banking Portal', { align: 'center' });

  doc.end();
});

module.exports = router;
